version: '3'

services:
  app:
    container_name: FastAPI
    build: .
    volumes:
      - .:/app
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind "0.0.0.0:8000" app.main:app
    env_file:
      - .env
