version: '3'

services:
  app:
    container_name: FastAPI
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    env_file:
      - .env
